name: uniconnect
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.10.0 
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.0.0
  cupertino_icons: ^1.0.8
  image_picker: ^0.8.4+8
  geolocator: ^8.2.0
  intl: ^0.18.0
  file_picker: ^5.0.0
  firebase_storage: ^11.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:

  uses-material-design: true

  assets:
    - lib/assets/img/
  